name: emoji_picker
description: A Flutter package that provides an Emoji Keyboard widget with 390 emojis in 8 categories.
version: 0.1.1
homepage: https://github.com/JeffG05/emoji_picker

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.4+1
  keyboard_actions: ^3.3.0
  bubble: ^1.1.9+1
  giphy_client: ^0.2.0
  cached_network_image: 2.2.0+1
  keyboard_visibility: ^0.5.6

  flutter_typeahead: ^1.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jeffg.emoji_picker
        pluginClass: EmojiPickerPlugin
      ios:
        pluginClass: EmojiPickerPlugin
